Repository koodikilpparit/sanapolku, pull requests merged in 2024-10, with the labels that each got.

#49 #46 Korjattu etusivun skaalautuvuus
  public/index.html
  src/pages/Start.css
Labels: UI

#51 33 Add Google's Lighthouse website analysis tool
  .github/workflows/lighthouse.yml
  lighthouserc.js
  package-lock.json
  package.json
Labels: CI/CD

#70 64 add pipeline check for lint
  .eslintrc
  .github/workflows/lint.yml
  .husky/pre-commit
  package-lock.json
  package.json
  src/db/db.test.js
Labels: CI/CD

#43 4 implement view for game instructions
  src/components/instructions/BackButton.js
  src/components/instructions/InstructionsText.js
  src/pages/Instructions.css
  src/pages/Instructions.js
  src/pages/Instructions.test.js
  src/pages/Start.css
  src/pages/Start.js
Labels: UI

#58 5 implement view for infopage
  package-lock.json
  src/contexts/SettingsContext.js
  src/contexts/SettingsContext.test.js
  src/db/db.js
  src/db/db.test.js
  src/index.js
  src/pages/Settings.js
  src/pages/Settings.test.js
  src/pages/Start.test.js
  src/styles/Settings.css
Labels: UI

#111 #109 Korjattu ikonien ja kuvankaappauksien polut toimimaan Pages-ympä…
  public/manifest.json
Labels: Bug
